In [2]:
import numpy as np
# 基础的构建方法
arr = np.array([1,2,3])
print(arr.ndim)
print(arr)

1
[1 2 3]


In [3]:
# COPY
arr1 = np.copy(arr) # 元素和原始的数组相同，但是不是同一个数组了
print(arr1)

[1 2 3]


In [4]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0 np.zeros((行，列))
arr = np.zeros((2,3),dtype = int) # 默认是小数，可以指定dtype
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [5]:
# 创建一维全0
arr = np.zeros((3,),dtype = int) # 把一行有多少元素写在前面，加一个逗号就可以
print(arr)

[0 0 0]


In [6]:
# 全1  np.ones((行，列))
arr = np.ones((5,8),dtype = int) # 默认是小数，可以指定dtype
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [7]:
# 未初始化  np.empty((行，列))
arr = np.empty((4,3)) # 只确定是两行三列的数组，先不填充值，生成的值都是随机的
print(arr)

[[1.13498946e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.37961641e-306 1.16278768e+165]
 [2.95954539e-032 6.74643107e-067 1.65713388e-076]
 [2.62242488e+180 4.66918287e-062 8.61115388e-067]]


In [8]:
# 固定值  np.full((行，列)，填充的值)
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [9]:
# zeros_like()  表示和某一个数组的结构是一样的，但值全为0
arr1 = np.zeros_like(arr)
print(arr1)
# ones_like
arr1 = np.ones_like(arr)
print(arr1)
# empty_like
arr1 = np.empty_like(arr)
print(arr1)
# full_like
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [10]:
# 等差数列
arr = np.arange(1,10,2)  # 左闭右开
print(arr)

[1 3 5 7 9]


In [11]:
# 等间隔数列
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
# 对数间隔数列
arr = np.logspace(0, 4, 3,base=2)  # 2^0  2^2  2^4  将0-4取三份,0  2  4，以2为底计算，默认是以十为底，可以通过base指定
print(arr)

[ 1.  4. 16.]


In [13]:
# 特殊矩阵的构造
# 单位矩阵：主对角线的元素为1，其余元素为0
arr = np.eye(3,dtype = int)  # 不指定具体的行列，输入3表示3*3
print(arr)
arr = np.eye(3,4,dtype = int)  # 指定具体的行列，表示3*4的单位矩阵
print(arr)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [14]:
# 对角矩阵：主对角线上是非零值，其余数字为0
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [15]:
# 随机数组的生成

In [16]:
# 某城市一周的最高气温（℃）为 [28, 30, 29, 31, 32, 30, 29]。  
# 计算平均气温、最高气温和最低气温。  
# 找出气温超过 30℃ 的天数。 

In [17]:
arr = np.array([28, 30, 29, 31, 32, 30, 29])
print("平均气温是",np.mean(arr))
print("最高气温是",np.max(arr))
print("最低气温是",np.min(arr))
print("气温超过 30℃ 的天数",np.size(np.where(arr>=30)))

平均气温是 29.857142857142858
最高气温是 32
最低气温是 28
气温超过 30℃ 的天数 4


In [18]:
"""
某班级 5 名学生的数学成绩为 [85, 90, 78, 92, 88]。  
•	计算成绩的平均分、中位数和标准差。  
•	将成绩转换为百分制（假设满分为 100）。
"""

'\n某班级 5 名学生的数学成绩为 [85, 90, 78, 92, 88]。  \n•\t计算成绩的平均分、中位数和标准差。  \n•\t将成绩转换为百分制（假设满分为 100）。\n'

In [19]:
score = np.array([85, 90, 78, 92, 88])
print("成绩的平均分是",np.mean(score))
print("成绩的中位数是",np.median(score))
print("成绩的标准差是",np.std(score))

成绩的平均分是 86.6
成绩的中位数是 88.0
成绩的标准差是 4.882622246293481


In [20]:
"""
给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。  
•	计算 A + B 和 A * B（逐元素乘法）。  
•	计算 A 和 B 的矩阵乘法（点积）。
"""

'\n给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。  \n•\t计算 A + B 和 A * B（逐元素乘法）。  \n•\t计算 A 和 B 的矩阵乘法（点积）。\n'

In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 + arr2)
print(arr1 * arr2)
print(arr1 @ arr2)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [22]:
"""
生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。  
•	计算每列的最大值和每行的最小值。  
•	将数组中的所有奇数替换为 -1。
"""

'\n生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。  \n•\t计算每列的最大值和每行的最小值。  \n•\t将数组中的所有奇数替换为 -1。\n'

In [23]:
np.random.seed(0)
arr = np.random.randint(0, 10, [3,4])
print(arr)
print("每列的最大值",np.max(arr, axis = 0))
print("每行的最小值",np.min(arr, axis = 1))
arr[arr%2==1] = -1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值 [7 9 7 6]
每行的最小值 [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [24]:
"""
创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组。  
•	计算每行的和与每列的平均值。  
•	将数组展平为一维数组。
"""

'\n创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组。  \n•\t计算每行的和与每列的平均值。  \n•\t将数组展平为一维数组。\n'

In [25]:
arr1 = np.arange(1, 13).reshape(3, 4)
print(arr1)
print("每行的和是",np.sum(arr1,axis=1))
print("每列的平均值是",np.mean(arr1, axis=0))
print("展平后",arr1.flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和是 [10 26 42]
每列的平均值是 [5. 6. 7. 8.]
展平后 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
"""
生成一个 (5, 5) 的随机数组，范围 [0, 20)。  
•	找出数组中大于 10 的元素。  
•	将所有大于 10 的元素替换为 0。 
"""

'\n生成一个 (5, 5) 的随机数组，范围 [0, 20)。  \n•\t找出数组中大于 10 的元素。  \n•\t将所有大于 10 的元素替换为 0。 \n'

In [27]:
np.random.seed(0)
arr1 = np.random.randint(0, 20, (5,5))
print(arr1)
print("大于 10 的元素",arr1[arr1>10])
arr1[arr1>10] = 0
print(arr1)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
大于 10 的元素 [12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [28]:
"""
某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。  
•	计算销售额的总和、均值和方差。  
•	找出销售额最高的月份和最低的月份。
"""

'\n某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。  \n•\t计算销售额的总和、均值和方差。  \n•\t找出销售额最高的月份和最低的月份。\n'

In [29]:
arr = np.array([120, 135, 110, 125, 130, 140])
print("销售额的总和、均值和方差分别为",np.sum(arr), np.mean(arr), np.var(arr))
print("销售额最高的月份",np.argmax(arr)+1)
print("销售额最低的月份",np.argmin(arr)+1)

销售额的总和、均值和方差分别为 760 126.66666666666667 97.22222222222223
销售额最高的月份 6
销售额最低的月份 3


In [30]:
"""
给定 A = [1, 2, 3] 和 B = [4, 5, 6]。  
•	水平拼接为 [1, 2, 3, 4, 5, 6]。  
•	垂直拼接为 [[1, 2, 3], [4, 5, 6]]。
"""

'\n给定 A = [1, 2, 3] 和 B = [4, 5, 6]。  \n•\t水平拼接为 [1, 2, 3, 4, 5, 6]。  \n•\t垂直拼接为 [[1, 2, 3], [4, 5, 6]]。\n'

In [31]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print("水平拼接为",np.concatenate((A,B)))
print("垂直拼接为\n",np.vstack((A,B)))

水平拼接为 [1 2 3 4 5 6]
垂直拼接为
 [[1 2 3]
 [4 5 6]]


In [32]:
"""
给定数组 [2, 1, 2, 3, 1, 4, 3]。  
•	找出唯一值并排序。  
•	计算每个唯一值出现的次数。
"""

'\n给定数组 [2, 1, 2, 3, 1, 4, 3]。  \n•\t找出唯一值并排序。  \n•\t计算每个唯一值出现的次数。\n'

In [33]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)
print(counts)

[1 2 3 4]
[2 2 2 1]


In [34]:
"""
给定数组 [1, np.nan, 3, np.nan, 5]。  
•	计算非缺失值的数量。  
•	将缺失值替换为 0。
"""

'\n给定数组 [1, np.nan, 3, np.nan, 5]。  \n•\t计算非缺失值的数量。  \n•\t将缺失值替换为 0。\n'

In [35]:
arr = np.array([1, np.nan, 3, np.nan, 5])
print("非缺失值数量:", np.sum(np.isnan(arr)))
arr[np.isnan(arr)] = 0
print(arr)

非缺失值数量: 2
[1. 0. 3. 0. 5.]
